
package com.finkok.facturacion.registration;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "http://facturacion.finkok.com/registration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * This function is in charge of editing an account, it will only be used by the resellers
     * 
     * @param resellerPassword
     * @param cer
     * @param resellerUsername
     * @param passphrase
     * @param taxpayerId
     * @param key
     * @param status
     * @return
     *     returns com.finkok.facturacion.registration.RegistrationResult
     */
    @WebMethod(action = "edit")
    @WebResult(name = "editResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "edit", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.EditResponse")
    public RegistrationResult edit(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId,
        @WebParam(name = "status", targetNamespace = "http://facturacion.finkok.com/registration")
        String status,
        @WebParam(name = "cer", targetNamespace = "http://facturacion.finkok.com/registration")
        byte[] cer,
        @WebParam(name = "key", targetNamespace = "http://facturacion.finkok.com/registration")
        byte[] key,
        @WebParam(name = "passphrase", targetNamespace = "http://facturacion.finkok.com/registration")
        String passphrase);

    /**
     * This function is in charge of adding a new user under the reseller, it will only be used by the resellers
     * 
     * @param resellerPassword
     * @param cer
     * @param coupon
     * @param resellerUsername
     * @param typeUser
     * @param added
     * @param passphrase
     * @param taxpayerId
     * @param key
     * @return
     *     returns com.finkok.facturacion.registration.RegistrationResult
     */
    @WebMethod(action = "add")
    @WebResult(name = "addResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "add", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.AddResponse")
    public RegistrationResult add(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId,
        @WebParam(name = "type_user", targetNamespace = "http://facturacion.finkok.com/registration")
        String typeUser,
        @WebParam(name = "coupon", targetNamespace = "http://facturacion.finkok.com/registration")
        String coupon,
        @WebParam(name = "added", targetNamespace = "http://facturacion.finkok.com/registration")
        String added,
        @WebParam(name = "cer", targetNamespace = "http://facturacion.finkok.com/registration")
        byte[] cer,
        @WebParam(name = "key", targetNamespace = "http://facturacion.finkok.com/registration")
        byte[] key,
        @WebParam(name = "passphrase", targetNamespace = "http://facturacion.finkok.com/registration")
        String passphrase);

    /**
     * This function added credit to Reselleruser
     * 
     * @param password
     * @param credit
     * @param taxpayerId
     * @param username
     * @return
     *     returns com.finkok.facturacion.registration.AssingResult
     */
    @WebMethod(action = "assign")
    @WebResult(name = "assignResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "assign", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.Assign")
    @ResponseWrapper(localName = "assignResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.AssignResponse")
    public AssingResult assign(
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/registration")
        String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/registration")
        String password,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId,
        @WebParam(name = "credit", targetNamespace = "http://facturacion.finkok.com/registration")
        BigInteger credit);

    /**
     * This function lists all the user of the account if no taxpayer_id is passed otherwise will return the taxpayer_id and status of the given user.
     * 
     * @param resellerPassword
     * @param resellerUsername
     * @param taxpayerId
     * @return
     *     returns com.finkok.facturacion.registration.RegistrationListResult
     */
    @WebMethod(action = "get")
    @WebResult(name = "getResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "get", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.finkok.facturacion.registration.GetResponse")
    public RegistrationListResult get(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId);

}
