
package com.finkok.facturacion.registration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistrationSOAP", targetNamespace = "http://facturacion.finkok.com/registration", wsdlLocation = "file:/Users/jp/Documents/IdeaProjects/finkok-ws/src/main/resources/registration.wsdl")
public class RegistrationSOAP
    extends Service
{

    private final static URL REGISTRATIONSOAP_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONSOAP_EXCEPTION;
    private final static QName REGISTRATIONSOAP_QNAME = new QName("http://facturacion.finkok.com/registration", "RegistrationSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/jp/Documents/IdeaProjects/finkok-ws/src/main/resources/registration.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONSOAP_WSDL_LOCATION = url;
        REGISTRATIONSOAP_EXCEPTION = e;
    }

    public RegistrationSOAP() {
        super(__getWsdlLocation(), REGISTRATIONSOAP_QNAME);
    }

    public RegistrationSOAP(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONSOAP_QNAME, features);
    }

    public RegistrationSOAP(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONSOAP_QNAME);
    }

    public RegistrationSOAP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONSOAP_QNAME, features);
    }

    public RegistrationSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(new QName("http://facturacion.finkok.com/registration", "Application"), Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(new QName("http://facturacion.finkok.com/registration", "Application"), Application.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONSOAP_EXCEPTION!= null) {
            throw REGISTRATIONSOAP_EXCEPTION;
        }
        return REGISTRATIONSOAP_WSDL_LOCATION;
    }

}
